"""adiciona estrutura inicial de fretes

Revision ID: 06cf4f4e222b
Revises: ca0788774ed2
Create Date: 2026-08-24 15:52:06.614889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06cf4f4e222b'
down_revision: Union[str, Sequence[str], None] = 'ca0788774ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freights',
    sa.Column('freight_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('primary_quote_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('fk_freights_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_freights_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['primary_quote_id'], ['quotes.quote_id'], name=op.f('fk_freights_primary_quote_id_quotes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('freight_id', name=op.f('pk_freights')),
    sa.UniqueConstraint('primary_quote_id', name='uq_freights_primary_quote_id')
    )
    op.create_index(op.f('ix_freights_created_at'), 'freights', ['created_at'], unique=False)
    op.create_index(op.f('ix_freights_customer_id'), 'freights', ['customer_id'], unique=False)
    op.create_foreign_key('fk_quotes_freight_id_freights', 'quotes', 'freights', ['freight_id'], ['freight_id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_quotes_freight_id_freights', 'quotes', type_='foreignkey')
    op.drop_index(op.f('ix_freights_customer_id'), table_name='freights')
    op.drop_index(op.f('ix_freights_created_at'), table_name='freights')
    op.drop_table('freights')
    # ### end Alembic commands ###
