"""cria estrutura inicial de orcamentos

Revision ID: 57b05da12d0d
Revises:
Create Date: 2026-08-18 17:54:35.531270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b05da12d0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('quote_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('quote_number', sa.String(length=50), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modality', sa.String(length=30), nullable=False),
    sa.Column('axle_count', sa.SmallInteger(), nullable=False),
    sa.Column('include_return_trip', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('distance', sa.String(length=100), nullable=False),
    sa.Column('valor_nota', sa.Numeric(), nullable=False),
    sa.Column('geral', sa.Numeric(), nullable=False),
    sa.Column('pedagio', sa.Numeric(), nullable=False),
    sa.Column('custo', sa.Numeric(), nullable=False),
    sa.Column('subtotal', sa.Numeric(), nullable=False),
    sa.Column('total', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('quote_id', name=op.f('pk_quotes')),
    sa.UniqueConstraint('quote_number', name=op.f('uq_quotes_quote_number'))
    )
    op.create_index(op.f('ix_quotes_issued_at'), 'quotes', ['issued_at'], unique=False)
    op.create_table('quote_taxes',
    sa.Column('quote_tax_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('quote_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.Numeric(), nullable=False),
    sa.Column('calculation_base', sa.Numeric(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.quote_id'], name=op.f('fk_quote_taxes_quote_id_quotes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quote_tax_id', name=op.f('pk_quote_taxes')),
    sa.UniqueConstraint('quote_id', 'position', name='uq_quote_taxes_quote_id_position')
    )
    op.create_index(op.f('ix_quote_taxes_quote_id'), 'quote_taxes', ['quote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_taxes_quote_id'), table_name='quote_taxes')
    op.drop_table('quote_taxes')
    op.drop_index(op.f('ix_quotes_issued_at'), table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
