"""reestrutura nucleo de orcamentos

Revision ID: 61ba7dfb049c
Revises: a69c319d51a7
Create Date: 2026-08-21 18:13:08.515055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61ba7dfb049c'
down_revision: Union[str, Sequence[str], None] = 'a69c319d51a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

        # A estrutura anterior de orçamento era
    # transitória e contém apenas dados de
    # desenvolvimento incompatíveis com o
    # novo modelo versionado.
    op.execute(
        "DELETE FROM quotes"
    )
    op.create_table('quote_number_counters',
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('last_value', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('year', name=op.f('pk_quote_number_counters'))
    )
    op.create_table('quote_versions',
    sa.Column('quote_version_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('quote_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.SmallInteger(), nullable=False),
    sa.Column('customer_person_type_snapshot', sa.String(length=2), nullable=False),
    sa.Column('customer_document_snapshot', sa.String(length=14), nullable=False),
    sa.Column('customer_legal_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('customer_trade_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('modality', sa.String(length=30), nullable=True),
    sa.Column('origin', sa.String(length=255), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('distance_km', sa.Numeric(), nullable=True),
    sa.Column('axle_count', sa.SmallInteger(), nullable=True),
    sa.Column('include_return_trip', sa.Boolean(), nullable=False),
    sa.Column('invoice_value', sa.Numeric(), nullable=True),
    sa.Column('tracking_required', sa.Boolean(), nullable=False),
    sa.Column('driver_amount', sa.Numeric(), nullable=True),
    sa.Column('toll_amount', sa.Numeric(), nullable=True),
    sa.Column('additional_total', sa.Numeric(), nullable=True),
    sa.Column('freight_insurance_total', sa.Numeric(), nullable=True),
    sa.Column('bp01', sa.Numeric(), nullable=True),
    sa.Column('administrative_rate', sa.Numeric(), nullable=True),
    sa.Column('administrative_minimum', sa.Numeric(), nullable=True),
    sa.Column('administrative_cost', sa.Numeric(), nullable=True),
    sa.Column('bp02', sa.Numeric(), nullable=True),
    sa.Column('margin_band_minimum', sa.Numeric(), nullable=True),
    sa.Column('margin_band_maximum', sa.Numeric(), nullable=True),
    sa.Column('standard_margin_rate', sa.Numeric(), nullable=True),
    sa.Column('standard_margin_value', sa.Numeric(), nullable=True),
    sa.Column('target_net_value', sa.Numeric(), nullable=True),
    sa.Column('tax_rate', sa.Numeric(), nullable=True),
    sa.Column('tax_value', sa.Numeric(), nullable=True),
    sa.Column('calculated_price', sa.Numeric(), nullable=True),
    sa.Column('rounded_price', sa.Numeric(), nullable=True),
    sa.Column('offered_price', sa.Numeric(), nullable=True),
    sa.Column('contracted_price', sa.Numeric(), nullable=True),
    sa.Column('offered_margin_value', sa.Numeric(), nullable=True),
    sa.Column('offered_margin_rate', sa.Numeric(), nullable=True),
    sa.Column('contracted_margin_value', sa.Numeric(), nullable=True),
    sa.Column('contracted_margin_rate', sa.Numeric(), nullable=True),
    sa.Column('validity_days_snapshot', sa.SmallInteger(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('internal_observation', sa.Text(), nullable=True),
    sa.Column('proposal_observation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('version_number >= 1', name='ck_quote_versions_version_number_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('fk_quote_versions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.quote_id'], name=op.f('fk_quote_versions_quote_id_quotes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quote_version_id', name=op.f('pk_quote_versions')),
    sa.UniqueConstraint('quote_id', 'quote_version_id', name='uq_quote_versions_quote_id_quote_version_id'),
    sa.UniqueConstraint('quote_id', 'version_number', name='uq_quote_versions_quote_id_version_number')
    )
    op.create_index(op.f('ix_quote_versions_quote_id'), 'quote_versions', ['quote_id'], unique=False)
    op.create_table('quote_additionals',
    sa.Column('quote_additional_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('quote_version_id', sa.BigInteger(), nullable=False),
    sa.Column('additional_type', sa.String(length=30), nullable=False),
    sa.Column('custom_description', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('position >= 1', name='ck_quote_additionals_position_positive'),
    sa.ForeignKeyConstraint(['quote_version_id'], ['quote_versions.quote_version_id'], name=op.f('fk_quote_additionals_quote_version_id_quote_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quote_additional_id', name=op.f('pk_quote_additionals')),
    sa.UniqueConstraint('quote_version_id', 'position', name='uq_quote_additionals_quote_version_id_position')
    )
    op.create_index(op.f('ix_quote_additionals_quote_version_id'), 'quote_additionals', ['quote_version_id'], unique=False)
    op.create_table('quote_events',
    sa.Column('quote_event_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('quote_id', sa.BigInteger(), nullable=False),
    sa.Column('quote_version_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=True),
    sa.Column('previous_amount', sa.Numeric(), nullable=True),
    sa.Column('new_amount', sa.Numeric(), nullable=True),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.quote_id'], name=op.f('fk_quote_events_quote_id_quotes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_version_id'], ['quote_versions.quote_version_id'], name=op.f('fk_quote_events_quote_version_id_quote_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_quote_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('quote_event_id', name=op.f('pk_quote_events'))
    )
    op.create_index(op.f('ix_quote_events_occurred_at'), 'quote_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_quote_events_quote_id'), 'quote_events', ['quote_id'], unique=False)
    op.create_index(op.f('ix_quote_events_quote_version_id'), 'quote_events', ['quote_version_id'], unique=False)
    op.create_table('quote_insurance_components',
    sa.Column('quote_insurance_component_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('quote_version_id', sa.BigInteger(), nullable=False),
    sa.Column('insurance_type', sa.String(length=30), nullable=False),
    sa.Column('calculation_base', sa.Numeric(), nullable=True),
    sa.Column('rate', sa.Numeric(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('position >= 1', name='ck_quote_insurance_components_position_positive'),
    sa.ForeignKeyConstraint(['quote_version_id'], ['quote_versions.quote_version_id'], name=op.f('fk_quote_insurance_components_quote_version_id_quote_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quote_insurance_component_id', name=op.f('pk_quote_insurance_components')),
    sa.UniqueConstraint('quote_version_id', 'position', name='uq_quote_insurance_components_quote_version_id_position')
    )
    op.create_index(op.f('ix_quote_insurance_components_quote_version_id'), 'quote_insurance_components', ['quote_version_id'], unique=False)
    op.drop_index(op.f('ix_quote_taxes_quote_id'), table_name='quote_taxes')
    op.drop_table('quote_taxes')
    op.add_column('quotes', sa.Column('quote_type', sa.String(length=20), nullable=False))
    op.add_column('quotes', sa.Column('customer_id', sa.BigInteger(), nullable=False))
    op.add_column('quotes', sa.Column('primary_quote_id', sa.BigInteger(), nullable=True))
    op.add_column('quotes', sa.Column('freight_id', sa.BigInteger(), nullable=True))
    op.add_column('quotes', sa.Column('current_status', sa.String(length=30), nullable=False))
    op.add_column('quotes', sa.Column('approved_version_id', sa.BigInteger(), nullable=True))
    op.add_column('quotes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('quotes', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.alter_column('quotes', 'quote_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_quotes_issued_at'), table_name='quotes')
    op.create_index(op.f('ix_quotes_created_at'), 'quotes', ['created_at'], unique=False)
    op.create_index(op.f('ix_quotes_current_status'), 'quotes', ['current_status'], unique=False)
    op.create_index(op.f('ix_quotes_customer_id'), 'quotes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_quotes_freight_id'), 'quotes', ['freight_id'], unique=False)
    op.create_index(op.f('ix_quotes_primary_quote_id'), 'quotes', ['primary_quote_id'], unique=False)
    op.create_check_constraint("ck_quotes_type_primary_quote","quotes",("(""quote_type = 'PRIMARY' ""AND primary_quote_id IS NULL"") OR (""quote_type = 'COMPLEMENTARY' ""AND primary_quote_id IS NOT NULL"")"))
    op.create_check_constraint("ck_quotes_not_self_primary","quotes",("primary_quote_id IS NULL ""OR primary_quote_id <> quote_id"))
    op.create_check_constraint("ck_quotes_approved_version","quotes",("(""current_status = 'APPROVED' ""AND approved_version_id IS NOT NULL"") OR (""current_status <> 'APPROVED' ""AND approved_version_id IS NULL"")"))
    op.create_foreign_key('fk_quotes_approved_version_quote_versions', 'quotes', 'quote_versions', ['quote_id', 'approved_version_id'], ['quote_id', 'quote_version_id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_quotes_created_by_users'), 'quotes', 'users', ['created_by'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_quotes_customer_id_customers'), 'quotes', 'customers', ['customer_id'], ['customer_id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_quotes_primary_quote_id_quotes'), 'quotes', 'quotes', ['primary_quote_id'], ['quote_id'], ondelete='RESTRICT')
    op.drop_column('quotes', 'valor_nota')
    op.drop_column('quotes', 'total')
    op.drop_column('quotes', 'subtotal')
    op.drop_column('quotes', 'include_return_trip')
    op.drop_column('quotes', 'destination')
    op.drop_column('quotes', 'issued_at')
    op.drop_column('quotes', 'modality')
    op.drop_column('quotes', 'distance')
    op.drop_column('quotes', 'pedagio')
    op.drop_column('quotes', 'custo')
    op.drop_column('quotes', 'origin')
    op.drop_column('quotes', 'axle_count')
    op.drop_column('quotes', 'geral')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # O modelo novo não possui conversão
    # reversível para a estrutura transitória
    # anterior.
    op.execute("DELETE FROM quotes")
    op.add_column('quotes', sa.Column('geral', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('quotes', sa.Column('axle_count', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('quotes', sa.Column('origin', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('quotes', sa.Column('custo', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('quotes', sa.Column('pedagio', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('quotes', sa.Column('distance', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('quotes', sa.Column('modality', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('quotes', sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('quotes', sa.Column('destination', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('quotes', sa.Column('include_return_trip', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('quotes', sa.Column('subtotal', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('quotes', sa.Column('total', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('quotes', sa.Column('valor_nota', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_constraint("ck_quotes_approved_version","quotes",type_="check")
    op.drop_constraint("ck_quotes_not_self_primary","quotes",type_="check")
    op.drop_constraint("ck_quotes_type_primary_quote","quotes",type_="check")
    op.drop_constraint(op.f('fk_quotes_primary_quote_id_quotes'), 'quotes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotes_customer_id_customers'), 'quotes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotes_created_by_users'), 'quotes', type_='foreignkey')
    op.drop_constraint('fk_quotes_approved_version_quote_versions', 'quotes', type_='foreignkey')
    op.drop_index(op.f('ix_quotes_primary_quote_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_freight_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_customer_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_current_status'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_created_at'), table_name='quotes')
    op.create_index(op.f('ix_quotes_issued_at'), 'quotes', ['issued_at'], unique=False)
    op.alter_column('quotes', 'quote_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('quotes', 'created_by')
    op.drop_column('quotes', 'created_at')
    op.drop_column('quotes', 'approved_version_id')
    op.drop_column('quotes', 'current_status')
    op.drop_column('quotes', 'freight_id')
    op.drop_column('quotes', 'primary_quote_id')
    op.drop_column('quotes', 'customer_id')
    op.drop_column('quotes', 'quote_type')
    op.create_table('quote_taxes',
    sa.Column('quote_tax_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('quote_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('position', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rate', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('calculation_base', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.quote_id'], name=op.f('fk_quote_taxes_quote_id_quotes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quote_tax_id', name=op.f('pk_quote_taxes')),
    sa.UniqueConstraint('quote_id', 'position', name=op.f('uq_quote_taxes_quote_id_position'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_quote_taxes_quote_id'), 'quote_taxes', ['quote_id'], unique=False)
    op.drop_index(op.f('ix_quote_insurance_components_quote_version_id'), table_name='quote_insurance_components')
    op.drop_table('quote_insurance_components')
    op.drop_index(op.f('ix_quote_events_quote_version_id'), table_name='quote_events')
    op.drop_index(op.f('ix_quote_events_quote_id'), table_name='quote_events')
    op.drop_index(op.f('ix_quote_events_occurred_at'), table_name='quote_events')
    op.drop_table('quote_events')
    op.drop_index(op.f('ix_quote_additionals_quote_version_id'), table_name='quote_additionals')
    op.drop_table('quote_additionals')
    op.drop_index(op.f('ix_quote_versions_quote_id'), table_name='quote_versions')
    op.drop_table('quote_versions')
    op.drop_table('quote_number_counters')
    # ### end Alembic commands ###
