"""adiciona cadastros de clientes

Revision ID: a69c319d51a7
Revises: 57b05da12d0d
Create Date: 2026-08-21 17:24:19.718493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69c319d51a7'
down_revision: Union[str, Sequence[str], None] = '57b05da12d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    op.create_table('customer_groups',
    sa.Column('customer_group_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('fk_customer_groups_created_by_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], name=op.f('fk_customer_groups_updated_by_users')),
    sa.PrimaryKeyConstraint('customer_group_id', name=op.f('pk_customer_groups'))
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('customer_group_id', sa.BigInteger(), nullable=True),
    sa.Column('person_type', sa.String(length=10), nullable=False),
    sa.Column('document', sa.String(length=14), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('state_registration', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('general_observation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('fk_customers_created_by_users')),
    sa.ForeignKeyConstraint(['customer_group_id'], ['customer_groups.customer_group_id'], name=op.f('fk_customers_customer_group_id_customer_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], name=op.f('fk_customers_updated_by_users')),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customers')),
    sa.UniqueConstraint('document', name=op.f('uq_customers_document'))
    )
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_customer_group_id'), 'customers', ['customer_group_id'], unique=False)
    op.create_table('customer_addresses',
    sa.Column('customer_address_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('address_type', sa.String(length=30), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('complement', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('fk_customer_addresses_created_by_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_customer_addresses_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], name=op.f('fk_customer_addresses_updated_by_users')),
    sa.PrimaryKeyConstraint('customer_address_id', name=op.f('pk_customer_addresses'))
    )
    op.create_index(op.f('ix_customer_addresses_customer_id'), 'customer_addresses', ['customer_id'], unique=False)
    op.create_index('uq_customer_addresses_customer_primary', 'customer_addresses', ['customer_id'], unique=True, postgresql_where=sa.text('is_primary IS TRUE'))
    op.create_table('customer_contacts',
    sa.Column('customer_contact_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('position_or_department', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('fk_customer_contacts_created_by_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_customer_contacts_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], name=op.f('fk_customer_contacts_updated_by_users')),
    sa.PrimaryKeyConstraint('customer_contact_id', name=op.f('pk_customer_contacts'))
    )
    op.create_index(op.f('ix_customer_contacts_customer_id'), 'customer_contacts', ['customer_id'], unique=False)
    op.create_index('uq_customer_contacts_customer_primary', 'customer_contacts', ['customer_id'], unique=True, postgresql_where=sa.text('is_primary IS TRUE'))
    op.create_table('customer_operational_locations',
    sa.Column('operational_location_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('complement', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('fk_customer_operational_locations_created_by_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_customer_operational_locations_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], name=op.f('fk_customer_operational_locations_updated_by_users')),
    sa.PrimaryKeyConstraint('operational_location_id', name=op.f('pk_customer_operational_locations'))
    )
    op.create_index(op.f('ix_customer_operational_locations_customer_id'), 'customer_operational_locations', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_operational_locations_customer_id'), table_name='customer_operational_locations')
    op.drop_table('customer_operational_locations')
    op.drop_index('uq_customer_contacts_customer_primary', table_name='customer_contacts', postgresql_where=sa.text('is_primary IS TRUE'))
    op.drop_index(op.f('ix_customer_contacts_customer_id'), table_name='customer_contacts')
    op.drop_table('customer_contacts')
    op.drop_index('uq_customer_addresses_customer_primary', table_name='customer_addresses', postgresql_where=sa.text('is_primary IS TRUE'))
    op.drop_index(op.f('ix_customer_addresses_customer_id'), table_name='customer_addresses')
    op.drop_table('customer_addresses')
    op.drop_index(op.f('ix_customers_customer_group_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('customer_groups')
    op.drop_table('users')
    # ### end Alembic commands ###
