from decimal import Decimal

from domain.models.quote_pricing_policy import (
    AdministrativeCostPolicy,
    MarginBand,
    QuotePricingPolicy
)


DEFAULT_QUOTE_PRICING_POLICY = (
    QuotePricingPolicy(
        administrative_cost_policies=(
            AdministrativeCostPolicy(
                tracking_required=False,
                rate=Decimal("0.04"),
                minimum_value=Decimal("200")
            ),
            AdministrativeCostPolicy(
                tracking_required=True,
                rate=Decimal("0.07"),
                minimum_value=Decimal("200")
            ),
        ),
        margin_bands=(
            MarginBand(
                lower_bound_exclusive=None,
                upper_bound_inclusive=Decimal(
                    "1000"
                ),
                rate=Decimal("0.25")
            ),
            MarginBand(
                lower_bound_exclusive=Decimal(
                    "1000"
                ),
                upper_bound_inclusive=Decimal(
                    "3000"
                ),
                rate=Decimal("0.22")
            ),
            MarginBand(
                lower_bound_exclusive=Decimal(
                    "3000"
                ),
                upper_bound_inclusive=Decimal(
                    "6000"
                ),
                rate=Decimal("0.18")
            ),
            MarginBand(
                lower_bound_exclusive=Decimal(
                    "6000"
                ),
                upper_bound_inclusive=Decimal(
                    "10000"
                ),
                rate=Decimal("0.18")
            ),
            MarginBand(
                lower_bound_exclusive=Decimal(
                    "10000"
                ),
                upper_bound_inclusive=Decimal(
                    "15000"
                ),
                rate=Decimal("0.18")
            ),
            MarginBand(
                lower_bound_exclusive=Decimal(
                    "15000"
                ),
                upper_bound_inclusive=Decimal(
                    "20000"
                ),
                rate=Decimal("0.16")
            ),
            MarginBand(
                lower_bound_exclusive=Decimal(
                    "20000"
                ),
                upper_bound_inclusive=Decimal(
                    "25000"
                ),
                rate=Decimal("0.156")
            ),
            MarginBand(
                lower_bound_exclusive=Decimal(
                    "25000"
                ),
                upper_bound_inclusive=Decimal(
                    "30000"
                ),
                rate=Decimal("0.15")
            ),
            MarginBand(
                lower_bound_exclusive=Decimal(
                    "30000"
                ),
                upper_bound_inclusive=Decimal(
                    "35000"
                ),
                rate=Decimal("0.15")
            ),
            MarginBand(
                lower_bound_exclusive=Decimal(
                    "35000"
                ),
                upper_bound_inclusive=Decimal(
                    "40000"
                ),
                rate=Decimal("0.15")
            ),
            MarginBand(
                lower_bound_exclusive=Decimal(
                    "40000"
                ),
                upper_bound_inclusive=Decimal(
                    "45000"
                ),
                rate=Decimal("0.15")
            ),
            MarginBand(
                lower_bound_exclusive=Decimal(
                    "45000"
                ),
                upper_bound_inclusive=Decimal(
                    "50000"
                ),
                rate=Decimal("0.15")
            ),
            MarginBand(
                lower_bound_exclusive=Decimal(
                    "50000"
                ),
                upper_bound_inclusive=None,
                rate=Decimal("0.15")
            ),
        ),
        tax_rate=Decimal("0.20")
    )
)